"""007_application_skill_match_schema

Revision ID: 6ebd6f31c63f
Revises: 4bb0f995173a
Create Date: 2026-09-08 11:52:28.123456

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ebd6f31c63f'
down_revision: Union[str, None] = '4bb0f995173a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_skill_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_application_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jd_skill_name', sa.String(length=255), nullable=False),
    sa.Column('jd_skill_slug', sa.String(length=255), nullable=False),
    sa.Column('match_status', sa.String(length=50), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], name=op.f('fk_application_skill_matches_job_application_id_job_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_application_skill_matches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_skill_matches'))
    )
    op.create_index(op.f('ix_application_skill_matches_id'), 'application_skill_matches', ['id'], unique=False)
    op.create_index(op.f('ix_application_skill_matches_job_application_id'), 'application_skill_matches', ['job_application_id'], unique=False)
    op.create_index(op.f('ix_application_skill_matches_user_id'), 'application_skill_matches', ['user_id'], unique=False)

    # Enable RLS
    op.execute("ALTER TABLE application_skill_matches ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE application_skill_matches FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_policy ON application_skill_matches "
        "USING (user_id = current_setting('app.current_tenant', true)::uuid);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON application_skill_matches;")
    op.drop_index(op.f('ix_application_skill_matches_user_id'), table_name='application_skill_matches')
    op.drop_index(op.f('ix_application_skill_matches_job_application_id'), table_name='application_skill_matches')
    op.drop_index(op.f('ix_application_skill_matches_id'), table_name='application_skill_matches')
    op.drop_table('application_skill_matches')
    # ### end Alembic commands ###
