"""006_interview_prep_schema

Revision ID: 4bb0f995173a
Revises: 005_tailoring_schema
Create Date: 2026-09-07 14:34:20.202057

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bb0f995173a'
down_revision: Union[str, None] = '005_tailoring_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_prep_sets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_application_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_application_id'], ['job_applications.id'], name=op.f('fk_interview_prep_sets_job_application_id_job_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_prep_sets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_prep_sets')),
    sa.UniqueConstraint('job_application_id', name=op.f('uq_interview_prep_sets_job_application_id'))
    )
    op.create_index(op.f('ix_interview_prep_sets_id'), 'interview_prep_sets', ['id'], unique=False)
    op.create_index(op.f('ix_interview_prep_sets_user_id'), 'interview_prep_sets', ['user_id'], unique=False)
    
    op.create_table('interview_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('prep_set_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('suggested_answer_outline', sa.Text(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('is_practiced', sa.Boolean(), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prep_set_id'], ['interview_prep_sets.id'], name=op.f('fk_interview_questions_prep_set_id_interview_prep_sets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interview_questions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions'))
    )
    op.create_index(op.f('ix_interview_questions_id'), 'interview_questions', ['id'], unique=False)
    op.create_index(op.f('ix_interview_questions_prep_set_id'), 'interview_questions', ['prep_set_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_user_id'), 'interview_questions', ['user_id'], unique=False)

    # Enable RLS
    op.execute("ALTER TABLE interview_prep_sets ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE interview_prep_sets FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_policy ON interview_prep_sets "
        "USING (user_id = current_setting('app.current_tenant', true)::uuid);"
    )
    
    op.execute("ALTER TABLE interview_questions ENABLE ROW LEVEL SECURITY;")
    op.execute("ALTER TABLE interview_questions FORCE ROW LEVEL SECURITY;")
    op.execute(
        "CREATE POLICY tenant_isolation_policy ON interview_questions "
        "USING (user_id = current_setting('app.current_tenant', true)::uuid);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON interview_questions;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON interview_prep_sets;")
    op.drop_index(op.f('ix_interview_questions_user_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_prep_set_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_interview_prep_sets_user_id'), table_name='interview_prep_sets')
    op.drop_index(op.f('ix_interview_prep_sets_id'), table_name='interview_prep_sets')
    op.drop_table('interview_prep_sets')
    # ### end Alembic commands ###
